a=int(input("Enter the number1"))
b=int(input("Enter the number2"))
print("Arithmetic:")
print("add",a+b)
print("sub",a-b)
print("mul",a*b)
print("div",a/b)
print("mod",a%b)
print("floordiv",a//b)
print("Exponent",a**b)
print("logicaland",a < 10 and b < 10)
print("logicalor",a <10 or b <10)
print("Conditional operator:")
print("greater",a>b)
print("less",a<b)
